### ISSUE TITLE
run on windows10 python3.5.1 pip-8.1.2

### ISSUE THREAD

**Issue by kudou** [liangqing/syncrypto#1]
windows10 x64 python3.5.1 pip-8.1.2
>syncrypto  f:\syn  f:\x

Traceback (most recent call last):
  File "d:\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python35\Scripts\syncrypto.exe\__main__.py", line 9, in <module>
  File "d:\python35\lib\site-packages\syncrypto\core.py", line 699, in main
    password = getpass(b'Please input the password:')
  File "d:\python35\lib\getpass.py", line 104, in win_getpass
    msvcrt.putwch(c)
TypeError: putwch() argument must be a unicode character, not int

**Comment by liangqing** [comment]
Thanks for your report, it is actually a bug
have fix it in version 0.4.1
you can upgrade by
`pip install syncrypto -U`
